authapp/urls.py
from django.urls import path
from authapp import views

app_name = "authapp"

urlpatterns = [
    path("login/", views.UserLogin.as_view(), name="login"),
    path("logout/", views.UserLogout.as_view(), name="logout"),
    path("registration/", views.UserRegistration.as_view(), name="registration"),
    path("profile/", views.UserProfile.as_view(), name="profile"),
    path("profile/<int:pk>/", views.UsersProfile.as_view(), name="users_profile"),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from blog import settings
from django.conf.urls.static import static
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("mainapp.urls", namespace="mainapp")),
    path("auth/", include("authapp.urls", namespace="authapp")),
    path("__debug__/", include(debug_toolbar.urls))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from mainapp import views

app_name = "mainapp"

urlpatterns = [
    path("", views.PostList.as_view(), name="post_list"),
    path("post/<int:pk>/", views.PostDetail.as_view(), name="post"),
    path("post/create/", views.PostCreate.as_view(), name="post_create"),
    path("post/update/<int:pk>/", views.PostUpdate.as_view(), name="post_update"),
    path("post/delete/<int:pk>/", views.PostDelete.as_view(), name="post_delete"),
    path("like_post/<int:pk>/", views.like, name="like_post"),
    
]

authapp/models.py
from django.db import models

# Create your models here.

mainapp/models.py
from django.db import models
from django.contrib.auth import get_user_model


class Post(models.Model):
    """
    Stores a posts
    Related to:
        :model: `User`
    """
    name = models.CharField(verbose_name='Название', max_length=256)
    text = models.TextField(verbose_name='Текст')
    img = models.ImageField(verbose_name='Картинка', upload_to="post_img", blank=True)
    time = models.TimeField(verbose_name='Время добавления/обновления', auto_now=True, auto_now_add=False)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, verbose_name='Пользователь')
    is_active = models.BooleanField(verbose_name='Активный', default=True)

    def __str__(self):
        return self.name

    def count_likes(self):
        return self.likes_set.all().count()

class Comments(models.Model):
    """
    Stores a comments for posts
    Related to:
        :model: `User`
        :model: `Post`
    """
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, verbose_name='Пользователь')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name='Пост')
    text = models.TextField(verbose_name='Текст')
    time = models.DateTimeField(verbose_name='Время добавления/обновления', auto_now=True, auto_now_add=False)

    def __str__(self):
        return self.text

class Likes(models.Model):
    """
    Stores a likes for posts
    Related to:
        :model: `User`
        :model: `Post`
    Double unique key:
        :field: `user`
        :field: `post`
    """
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, verbose_name='Пользователь')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name='Пост')
    
    class Meta:
        unique_together = ("user", "post")

authapp/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django.contrib.auth.views import get_user_model

class LoginForm(AuthenticationForm):
    """
    Form to login

    **Fields**
    :field: `username`
    :field: `password`
    """
    class Meta:
        model = get_user_model()
        fields = ("username", "password")

class RegistrationForm(UserCreationForm):
    """
    Form to registration

    **Fields**
    :field: `username`
    :field: `email`
    """
    class Meta:
        model = get_user_model()
        fields = ('username', 'email')


class UserProfileForm(UserChangeForm):
    """
    Form to change profole

    **Fields**
    :field: `username`
    :field: `email`
    :field: `first_name`
    :field: `last_name`
    """
    class Meta:
        model = get_user_model()
        fields = ('username', 'email', 'first_name', 'last_name')
        

authapp/views.py
from django.views.generic import FormView, RedirectView, CreateView, DetailView, UpdateView
from django.contrib.auth.views import get_user_model
from django.http import HttpResponseRedirect
from authapp.forms import LoginForm, RegistrationForm, UserProfileForm
from django.contrib.auth import login, logout
from django.contrib.auth.models import User



class UserLogin(FormView):
    """
    Provides users the ability to login
    """
    form_class = LoginForm
    template_name = 'authapp/login.html'
    success_url = '/'

    def form_valid(self, form):
        if form.get_user().is_active:
            login(self.request, form.get_user())
        return HttpResponseRedirect(self.get_success_url())


class UserLogout(RedirectView):
    """
    Provides users the ability to logout
    """
    url = '/'

    def get(self, request, *args, **kwargs):
        logout(request)
        return super(UserLogout, self).get(request, *args, **kwargs)


class UserRegistration(CreateView):
    """
    Provides users the ability to registration
    """
    form_class = RegistrationForm
    template_name = 'authapp/registration.html'
    success_url = '/'


class UsersProfile(DetailView):
    """
    Display user profile

    **Context**
    :model: `User`

    **Template**
    :template: `authapp/user_profile.html`
    """
    model = get_user_model()
    template_name = 'authapp/user_profile.html'


class UserProfile(UpdateView):
    """
    Provides users the ability to change profile
    """
    form_class = UserProfileForm
    model = get_user_model()
    template_name = 'authapp/profile.html'
    success_url = '/'

    def get_object(self, queryset=None):
        return self.request.user

authapp/templates/authapp/login.html
{% extends "mainapp/root.html"%}
{% load static %}

{% block content %}
    {% include "mainapp/includes/inc__menu.html" %}

    <form class="auth" method="POST">
        <h1 class="top">Форма входа</h1>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Login">
    </form>
{% endblock %}

authapp/templates/authapp/profile.html
{% extends "mainapp/root.html"%}
{% load static %}

{% block content %}
    {% include "mainapp/includes/inc__menu.html" %}

    <div class="auth">
    <p><h1>Personal account</h1></p>
        <form class="content" method="POST">
            {% csrf_token %}
            {{ form.username.label }}
            {{ form.username }}
            {{ form.email.label }}
            {{ form.email }}
            {{ form.first_name.label }}
            {{ form.first_name }}
            {{ form.last_name.label }}
            {{ form.last_name }}
            <input type="submit" value="Change">
            <h2><a href="{% url 'authapp:users_profile' pk=request.user.pk %}">Просмотреть профиль</a></h2>
        </form>

        <hr>
        <h1><p> Список постов:</p></h1>
        <form>
        {% for post in request.user.post_set.all %}
            <hr>    
            <h3 class="left"><p>{{ post }}</p></h3>
            <a href="{% url 'mainapp:post_update' pk=post.pk %}">Изменить</a>
            <a href="{% url 'mainapp:post_delete' pk=post.pk %}">Удалить</a>
            <hr>
        {% endfor %}
        </form>
    </div>
{% endblock %}

authapp/templates/authapp/registration.html
{% extends "mainapp/root.html"%}
{% load static %}

{% block content %}
    {% include "mainapp/includes/inc__menu.html" %}

    <form class="auth" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Registration">
    </form>
{% endblock %}

authapp/templates/authapp/user_profile.html
{% extends "mainapp/root.html"%}
{% load static %}

{% block content %}
    {% include "mainapp/includes/inc__menu.html" %}

    <div class="auth">
        <form>
            <h1><p>Пользователь: {{ object.username }}</p></h1>
            <h1><p>Имя: {{ object.first_name }}</p></h1>
            <h1><p>Фамилия: {{ object.last_name }}</p></h1>            
        </form>
        {% for post in object.post_set.all %}
            {% if post.is_active %}
                <cntr><a href="{% url 'mainapp:post' pk=post.pk %}"><p>{{ post }}</p></a></cntr>
                <hr>
            {% endif %}
        {% endfor %}
    </div>
    
{% endblock %}