authapp/urls.py
from django.urls import path
from authapp import views

app_name = "authapp"

urlpatterns = [
    path("login/", views.UserLogin.as_view(), name="login"),
    path("logout/", views.UserLogout.as_view(), name="logout"),
    path("registration/", views.UserRegistration.as_view(), name="registration"),
    path("profile/", views.UserProfile.as_view(), name="profile"),
    path("profile/<int:pk>/", views.UsersProfile.as_view(), name="users_profile"),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from blog import settings
from django.conf.urls.static import static
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("mainapp.urls", namespace="mainapp")),
    path("auth/", include("authapp.urls", namespace="authapp")),
    path("__debug__/", include(debug_toolbar.urls))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from mainapp import views

app_name = "mainapp"

urlpatterns = [
    path("", views.PostList.as_view(), name="post_list"),
    path("post/<int:pk>/", views.PostDetail.as_view(), name="post"),
    path("post/create/", views.PostCreate.as_view(), name="post_create"),
    path("post/update/<int:pk>/", views.PostUpdate.as_view(), name="post_update"),
    path("post/delete/<int:pk>/", views.PostDelete.as_view(), name="post_delete"),
    path("like_post/<int:pk>/", views.like, name="like_post"),
    
]

mainapp/models.py
from django.db import models
from django.contrib.auth import get_user_model


class Post(models.Model):
    """
    Stores a posts
    Related to:
        :model: `User`
    """
    name = models.CharField(verbose_name='Название', max_length=256)
    text = models.TextField(verbose_name='Текст')
    img = models.ImageField(verbose_name='Картинка', upload_to="post_img", blank=True)
    time = models.TimeField(verbose_name='Время добавления/обновления', auto_now=True, auto_now_add=False)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, verbose_name='Пользователь')
    is_active = models.BooleanField(verbose_name='Активный', default=True)

    def __str__(self):
        return self.name

    def count_likes(self):
        return self.likes_set.all().count()

class Comments(models.Model):
    """
    Stores a comments for posts
    Related to:
        :model: `User`
        :model: `Post`
    """
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, verbose_name='Пользователь')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name='Пост')
    text = models.TextField(verbose_name='Текст')
    time = models.DateTimeField(verbose_name='Время добавления/обновления', auto_now=True, auto_now_add=False)

    def __str__(self):
        return self.text

class Likes(models.Model):
    """
    Stores a likes for posts
    Related to:
        :model: `User`
        :model: `Post`
    Double unique key:
        :field: `user`
        :field: `post`
    """
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, verbose_name='Пользователь')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name='Пост')
    
    class Meta:
        unique_together = ("user", "post")

mainapp/forms.py
import django.forms as forms
from mainapp.models import Comments, Post


class CommentForm(forms.ModelForm):
    """
    Form to add comment

    **Fields**
    :field: `user_id`
    :field: `post_id`
    :field: `text`
    """
    class Meta:
        model = Comments
        fields = ("user", "post", "text")


class PostForm(forms.ModelForm):
    """
    Form to add post

    **Fields**
    :field: `name`
    :field: `text`
    :field: `img`
    :field: `user`
    """
    class Meta:
        model = Post
        fields = ("name", "text", "img", "user")


class PostUpdateForm(forms.ModelForm):
    """
    Form to add post

    **Fields**
    :field: `name`
    :field: `text`
    :field: `img`
    """
    class Meta:
        model = Post
        fields = ("name", "text", "img", "is_active")

mainapp/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, FormView, CreateView, UpdateView, DeleteView
from mainapp.models import Post, Likes
from mainapp.forms import CommentForm, PostForm, PostUpdateForm
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin


class PostList(ListView):
    """
    Display all post from model.Post and their cooments

    **Context**
    :model: `mainapp.models.Post`

    **Template**
    :template: `mainapp/post_list.html`
    """
    model = Post

    def get_queryset(self):
        return self.model.objects.filter(is_active=True).only('name','img','pk')


class PostDetail(DetailView):
    """
    Display post and comments where post_pk = pk

    **Context**
    :model: `mainapp.models.Post`
    :form: `mainapp.forms.CommentForm`

    **Template**
    :template: `mainapp/post_detail.html`
    """
    model = Post

    def get_queryset(self):
        return self.model.objects.filter(is_active=True).only('name','img','pk','user','time','text','is_active')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context["comment_form"] = CommentForm()
        context["comments"] = kwargs['object'].comments_set.all().select_related("user")
        return context

    def post(self, request, pk):
        form = CommentForm(data=request.POST)
        if form.is_valid():
            form.save()
        return HttpResponseRedirect(reverse("mainapp:post", kwargs={"pk":pk}))


class PostCreate(LoginRequiredMixin, CreateView):
    """
    Display form to create a post

    **Context**
    :model: `mainapp.models.Post`
    :form: `mainapp.forms.PostForm`

    **Template**
    :template: `mainapp/post_create.html`
    """
    model = Post
    form_class = PostForm
    template_name = 'mainapp/post_create.html'

    def post(self, request):
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
        return HttpResponseRedirect(reverse("authapp:users_profile", kwargs={"pk":request.user.pk}))


class PostUpdate(LoginRequiredMixin, UpdateView):
    """
    Display form to update a post

    **Context**
    :model: `mainapp.models.Post`
    :form: `mainapp.forms.PostUpdateForm`

    **Template**
    :template: `mainapp/post_update.html`
    """
    form_class = PostUpdateForm
    model = Post
    template_name = 'mainapp/post_update.html'
    success_url = '/'

    def get_object(self, get_queryset=None):
        post = super(PostUpdate, self).get_object()
        if not post.user == self.request.user:
            raise Http404
        return post


class PostDelete(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = '/'

    def get_object(self, get_queryset=None):
        post = super(PostDelete, self).get_object()
        if not post.user == self.request.user:
            raise Http404
        return post


@login_required
def like(request, pk):
    """
    Add functionals of likes
    """
    try:
        like = Likes()
        like.user = request.user
        like.post = Post.objects.filter(pk=pk).first()
        like.save()
    except Exception:
        like = Likes.objects.filter(user=request.user.pk, post=pk).first()
        like.delete()
    return HttpResponseRedirect(reverse("mainapp:post", kwargs={"pk":pk}))

mainapp/templates/mainapp/post_confirm_delete.html
{% extends "mainapp/root.html"%}
{% load static %}

{% block content %}
    {% include "mainapp/includes/inc__menu.html" %}

    <form class="auth" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <hr>
        <h2><p>Уверены что хотите удалить: {{ object }}</p></h2>
        <input type="submit" value="Удалить">
        <hr>
    </form>
{% endblock %}

mainapp/templates/mainapp/post_create.html
{% extends "mainapp/root.html"%}
{% load static %}

{% block content %}
    {% include "mainapp/includes/inc__menu.html" %}

    <div class="auth">
        <form class="big" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="">Тема:</label>
        {{ form.name }}
        <br>
        <label for="">Картинка:</label>
        {{ form.img }}
        <br>
        <label for="">Текст:</label>
        {{ form.text }}
        <br>
        <input type="hidden" name="user" id="id_user" value="{{ request.user.pk }}">
        <input type="submit" value="Create">
        </form>
    </div>
{% endblock %}

mainapp/templates/mainapp/post_detail.html
{% extends "mainapp/root.html"%}
{% load static %}

{% block content %}
    {% include "mainapp/includes/inc__menu.html" %}

    <div class="auth">
        <div class="large">
            <hr>
            <h1><p>{{ object.name }}</p></h1>
                <cntr><img src="/media/{{ object.img }}" width="600px" alt="#"></p></cntr>
            <hr>
            <h3>{{ object.text }}</h3>
            <hr>
            <sign>
                <p><p>Автор: <a class="user" href="{% url 'authapp:users_profile' pk=object.user_id %}">{{ object.user }}</a>
                    <p> at {{ object.time }}</p>
            </sign>

            <h3 class="right">Likes: {{ object.count_likes }}
            <p><a href="{% url 'mainapp:like_post' pk=object.pk %}">Лайк</a></p>
            </h3>
                {% if user.is_authenticated %}
                    <cntr><p>Напишите комментарий:</p></cntr>
                    <form method="POST">
                        {% csrf_token %}
                        {{ comment_form.text }}
                        <p><input type="hidden" name="user" id="id_user" value="{{ request.user.pk }}"></p>
                        <p><input type="hidden" name="post" id="id_post" value="{{ object.pk }}"></p>
                        <p><input type="submit" value="Отправить"></p>
                    </form>
                {% endif %}
        </div>

        <h2><p>Comments:</p></h2>
        {% for comment in comments %}
            <form>
                <h3 class="left"><p>{{ comment.user }}</p></h3>
                <p>Time: {{ comment.time }}</p>
                <hr>
                <p>{{ comment.text }}</p>
            </form>
        {% endfor %}
    </div>
{% endblock %}

mainapp/templates/mainapp/post_list.html
{% extends "mainapp/root.html"%}
{% load static %}

{% block content %}
    {% include "mainapp/includes/inc__menu.html" %}

    <div class="auth">
            {% for post in object_list %}
            <form class="large">
                <hr>
                <h1>{{ post.name }}</h1>
                <cntr><p><img src="media/{{post.img}}" width="600px" alt="#пост разружен без фото "></p></cntr>
                <h3 class="right"><a href="{% url 'mainapp:post' pk=post.pk %}">Подробнее</a></h3>
                <hr>
            </form>
            {% endfor %}
    </div>
{% endblock %}

mainapp/templates/mainapp/post_update.html
{% extends "mainapp/root.html"%}
{% load static %}

{% block content %}
    {% include "mainapp/includes/inc__menu.html" %}
    <div class="auth">
        <form class="big" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <label>Тема:</label>
            {{ form.name }}
            <br>
            <label>Изображение:</label>
            {{ form.img }}
            <label>Текст:</label>
            {{ form.text }}
            <br>
            <label>Черновик:</label>
            {{ form.is_active }}
            <br>
            <input type="submit" value="Update">
        </form>
    </div>
{% endblock %}

mainapp/templates/mainapp/root.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ITCat</title>
    <link href="{% static 'styles/auth.css' %}" rel="stylesheet">
    <link href="{% static 'styles/menu.css' %}" rel="stylesheet">
</head>

<body>
    <div class="content">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>